export const GET_RECIPES = "GET_RECIPES";
export const CREATE_RECIPE = "CREATE_RECIPE";
export const UPDATE_RECIPE = "UPDATE_RECIPE";
export const GET_RECOMMENDED_RECIPES = "GET_RECOMMENDED_RECIPES";

export const GET_SIMILAR_INGREDIENTS = "GET_SIMILAR_INGREDIENTS";
export const GET_INGREDIENTS = "GET_INGREDIENTS";
export const CREATE_INGREDIENT = "CREATE_INGREDIENT";
export const UPDATE_INGREDIENT = "UPDATE_INGREDIENT";